#!/bin/sh

# configure script for FlexibleSUSY
# Author: Alexander Voigt

if test $# -lt 1 ; then
    echo "Error: Too few arguments"
    echo "Usage: ./`basename $0` <model-name>"
    exit 1
fi

# directory of this script
BASEDIR=$(dirname $0)
overwrite="no"
models=""

#_____________________________________________________________________
help() {
    echo "Usage: ./`basename $0` [options] --models=<model1>{,<model2>}"
    echo "Options:"
    echo "--force,-f     Overwrite existing model files"
    echo "--models=      Comma separated list of models to create"
    echo "               The class name can be specified before a :"
    echo "               Sub-models can be specified after a /"
    echo "               Syntax: [classname:]model[/submodel]"
    echo "               Example: --models=MSSM,E6SSM/NoTEMP,MSSMCKM:MSSM/CKM"
    echo "--help,-h      Print this help message"
}

if test $# -gt 0 ; then
    while test ! "x$1" = "x" ; do
        case "$1" in
            -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
            *)    optarg= ;;
        esac

        case $1 in
            --force|-f)              overwrite="yes" ;;
            --help|-h)               help; exit 0 ;;
            --models=*)              models=`echo $optarg | tr ',' ' '` ;;
            *)  echo "Invalid option '$1'. Try $0 --help" ; exit 1 ;;
        esac
        shift
    done
fi

if [ -z "$models" ] ; then
    echo "Error: no model specified!"
    help
fi

for model in ${models}; do
    sub_model=$(echo $model | awk -F / '{ if (NF > 1) print $NF }')
    class_name=$(echo $model | awk -F : '{ if (NF > 1) print $1 }')
    model=$(echo $model | awk -F : '{ print $NF }' | awk -F / '{ print $1 }')

    # if the user has not provided a class name, use the model name as
    # class name
    if [ -z "$class_name" ]; then
        class_name="$model"
    fi

    # create target directory name
    targetdir="models/${class_name}"

    if test -d "$targetdir" -a "x$overwrite" = "xno" ; then
        echo "Error: directory $targetdir already exists!"
        echo "Please chose another model name or use the --force option."
        echo "See ./`basename $0` --help for more information."
        continue
    fi

    if [ -n "$sub_model" ]; then
        echo "creating model $class_name (SARAH model: $model, sub-model: $sub_model)"
    else
        echo "creating model $class_name (SARAH model: $model)"
    fi

    if test ! -d "$targetdir" ; then
        printf "  creating model directory %s ... " "$targetdir"
        mkdir $targetdir
        echo "done"
    fi

    printf "  creating Makefile module %s/module.mk ... " "$targetdir"
    sed -e "s|@DIR@|$targetdir|g"         \
        -e "s|@MODEL@|$model|g"           \
        -e "s|@CLASSNAME@|$class_name|g"  \
        < templates/module.mk.in > $targetdir/module.mk
    echo "done"

    printf "  creating start script %s/start.m ... " "$targetdir"
    sub_model_replacement=""
    if [ -n "$sub_model" ]; then
        sub_model_replacement=", \"$sub_model\""
    fi
    sed -e "s|@DIR@|$targetdir|g"         \
        -e "s|@ModelName@|$model|g"       \
        -e "s|@SubModel@|$sub_model_replacement|g"    \
        -e "s|@CLASSNAME@|$class_name|g"  \
        < templates/start.m.in > $targetdir/start.m
    echo "done"

    # if we provide a FlexibleSUSY model file for this class name, we
    # use this one
    modelFileDir="templates"
    if test -d "$modelFileDir/$class_name" ; then
        modelFileDir="$modelFileDir/$class_name"
        echo "  using predefined model files from $modelFileDir"
    else
        echo "  using default model files from $modelFileDir"
    fi

    printf "  creating FlexibleSUSY model file %s/FlexibleSUSY.m ... " "$targetdir"
    sed -e "s|@DIR@|$targetdir|g"         \
        -e "s|@ModelName@|$model|g"       \
        -e "s|@CLASSNAME@|$class_name|g"  \
        < $modelFileDir/FlexibleSUSY.m.in > $targetdir/FlexibleSUSY.m
    echo "done"
done
