#!/bin/sh

tanb_npoints=10
m0_npoints=10
subprocess=""
make_nice=""
niceness="5"

scan_MSSM() {
    echo "scanning MSSM ... "
    ${make_nice} ./higgs-study/scan_MSSM.x --tanb-npoints=${tanb_npoints} --m0-npoints=${m0_npoints} > higgs-study/data/scan_MSSM.dat
    echo "done MSSM"
}

scan_NMSSM() {
    if test $# -ne 1 ; then
        echo "scan_NMSSM: Too few arguments"
        return 1
    fi

    lambda="$1"

    echo "scanning NMSSM (lambda=${lambda}) ... "
    ${make_nice} ./higgs-study/scan_NMSSM.x --lambda=${lambda} --tanb-npoints=${tanb_npoints} --m0-npoints=${m0_npoints} > higgs-study/data/scan_NMSSM_lambda-${lambda}.dat
    echo "done NMSSM (lambda=${lambda})"
}

scan_phdUMSSM() {
    if test $# -ne 2 ; then
        echo "scan_phdUMSSM: Too few arguments"
        return 1
    fi

    lambda="$1"
    vs="$2"

    echo "scanning phdUMSSM (lambda=${lambda}, vs=${vs}) ... "
    ${make_nice} ./higgs-study/scan_phdUMSSM.x --lambda=${lambda} --vs=${vs} --tanb-npoints=${tanb_npoints} --m0-npoints=${m0_npoints} > higgs-study/data/scan_phdUMSSM_lambda-${lambda}_vs-${vs}.dat
    echo "done phdUMSSM (lambda=${lambda}, vs=${vs})"
}

scan_phdE6SSM() {
    if test $# -ne 3 ; then
        echo "scan_phdE6SSM: Too few arguments"
        return 1
    fi

    lambda="$1"
    vs="$2"
    kappa="$3"

    echo "scanning phdE6SSM (lambda=${lambda}, vs=${vs}, kappa=${kappa}) ... "
    ${make_nice} ./higgs-study/scan_phdE6SSM.x --lambda=${lambda} --vs=${vs} --kappa=${kappa} --tanb-npoints=${tanb_npoints} --m0-npoints=${m0_npoints} > higgs-study/data/scan_phdE6SSM_lambda-${lambda}_vs-${vs}_kappa-${kappa}.dat
    echo "done phdE6SSM (lambda=${lambda}, vs=${vs}, kappa=${kappa})"
}

help() {
cat <<EOF
Usage: ./`basename $0` [options]
Options:

  --help,-h         Print this help message

  --tanb-npoints=   number of tan(beta) points
  --m0-npoints=     number of m0 points
  --parallelize     start sub-process for each function
EOF
}

if test $# -gt 0 ; then
    while test ! "x$1" = "x" ; do
        case "$1" in
            -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
            *) optarg= ;;
        esac

        case $1 in
            --tanb-npoints=*)        tanb_npoints=$optarg ;;
            --m0-npoints=*)          m0_npoints=$optarg ;;
            --parallelize)
                subprocess="&"
                make_nice="nice -n ${niceness}"
                ;;
            --help|-h)               help; exit 0 ;;
            *)  echo "Invalid option '$1'. Try $0 --help" ; exit 1 ;;
        esac
        shift
    done
fi

echo "# number of tan(beta) points: ${tanb_npoints}"
echo "# number of m0 points:        ${m0_npoints}"

eval scan_MSSM ${subprocess}

# lambda
eval scan_NMSSM 0.1 ${subprocess}
eval scan_NMSSM 0.2 ${subprocess}
eval scan_NMSSM 0.4 ${subprocess}
eval scan_NMSSM 0.6 ${subprocess}
eval scan_NMSSM 0.8 ${subprocess}
eval scan_NMSSM 1.0 ${subprocess}

# lambda vs
eval scan_phdUMSSM 0.1 10000 ${subprocess}
eval scan_phdUMSSM 0.2 10000 ${subprocess}
eval scan_phdUMSSM 0.4 10000 ${subprocess}
eval scan_phdUMSSM 0.6 10000 ${subprocess}
eval scan_phdUMSSM 0.8 10000 ${subprocess}
eval scan_phdUMSSM 1.0 10000 ${subprocess}

# lambda vs kappa
eval scan_phdE6SSM 0.1 10000 0.1 ${subprocess}
eval scan_phdE6SSM 0.2 10000 0.1 ${subprocess}
eval scan_phdE6SSM 0.4 10000 0.1 ${subprocess}
eval scan_phdE6SSM 0.6 10000 0.1 ${subprocess}
eval scan_phdE6SSM 0.8 10000 0.1 ${subprocess}
eval scan_phdE6SSM 1.0 10000 0.1 ${subprocess}

eval scan_phdE6SSM 0.1 10000 0.2 ${subprocess}
eval scan_phdE6SSM 0.2 10000 0.2 ${subprocess}
eval scan_phdE6SSM 0.4 10000 0.2 ${subprocess}
eval scan_phdE6SSM 0.6 10000 0.2 ${subprocess}
eval scan_phdE6SSM 0.8 10000 0.2 ${subprocess}
eval scan_phdE6SSM 1.0 10000 0.2 ${subprocess}

eval scan_phdE6SSM 0.1 10000 0.4 ${subprocess}
eval scan_phdE6SSM 0.2 10000 0.4 ${subprocess}
eval scan_phdE6SSM 0.4 10000 0.4 ${subprocess}
eval scan_phdE6SSM 0.6 10000 0.4 ${subprocess}
eval scan_phdE6SSM 0.8 10000 0.4 ${subprocess}
eval scan_phdE6SSM 1.0 10000 0.4 ${subprocess}

eval scan_phdE6SSM 0.1 10000 0.6 ${subprocess}
eval scan_phdE6SSM 0.2 10000 0.6 ${subprocess}
eval scan_phdE6SSM 0.4 10000 0.6 ${subprocess}
eval scan_phdE6SSM 0.6 10000 0.6 ${subprocess}
eval scan_phdE6SSM 0.8 10000 0.6 ${subprocess}
eval scan_phdE6SSM 1.0 10000 0.6 ${subprocess}

eval scan_phdE6SSM 0.1 10000 0.8 ${subprocess}
eval scan_phdE6SSM 0.2 10000 0.8 ${subprocess}
eval scan_phdE6SSM 0.4 10000 0.8 ${subprocess}
eval scan_phdE6SSM 0.6 10000 0.8 ${subprocess}
eval scan_phdE6SSM 0.8 10000 0.8 ${subprocess}
eval scan_phdE6SSM 1.0 10000 0.8 ${subprocess}

eval scan_phdE6SSM 0.1 10000 1.0 ${subprocess}
eval scan_phdE6SSM 0.2 10000 1.0 ${subprocess}
eval scan_phdE6SSM 0.4 10000 1.0 ${subprocess}
eval scan_phdE6SSM 0.6 10000 1.0 ${subprocess}
eval scan_phdE6SSM 0.8 10000 1.0 ${subprocess}
eval scan_phdE6SSM 1.0 10000 1.0 ${subprocess}

wait
