#!/bin/sh

scan_MSSM() {
    echo -n "scanning MSSM ... "
    ./higgs-study/scan_MSSM.x > higgs-study/data/scan_MSSM.dat
    echo "done"
}

scan_NMSSM() {
    if test $# -ne 1 ; then
        echo "scan_NMSSM: Too few arguments"
        return 1
    fi

    lambda="$1"

    echo -n "scanning NMSSM (lambda=${lambda}) ... "
    ./higgs-study/scan_NMSSM.x --lambda=${lambda} > higgs-study/data/scan_NMSSM_lambda-${lambda}.dat
    echo "done"
}

scan_MSSM

scan_NMSSM 0.1
scan_NMSSM 0.2
scan_NMSSM 0.4
scan_NMSSM 0.6
scan_NMSSM 0.8
scan_NMSSM 1.0
