.TH FlexibleSUSY 1 "Januar 23, 2012" "version 0.1" "USER COMMANDS"
.SH NAME
FlexibleSUSY \- A spectrum generator for SUSY models
.SH SYNOPSIS
.B FlexibleSUSY
.RI [ OPTIONS ]
.SH DESCRIPTION
.PP
FlexibleSUSY is a spectrum generator for SUSY models.
.SH OPTIONS
None
.SH SEE ALSO
.BR SoftSusy
.PP
FlexibleSUSY website:
.B http://flexiblesusy.hepforge.org/
.SH COPYRIGHT
FlexibleSUSY Copyright (C) 2012 Alexander Voigt
<Alexander.Voigt@physik.tu-dresden.de>

FlexibleSUSY is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at
your option) any later version.

FlexibleSUSY is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with FlexibleSUSY.  If not, see <http://www.gnu.org/licenses/>.
