(* ::Package:: *)

(* :Copyright:

   ====================================================================
   This file is part of FlexibleSUSY.

   FlexibleSUSY is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published
   by the Free Software Foundation, either version 3 of the License,
   or (at your option) any later version.

   FlexibleSUSY is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with FlexibleSUSY.  If not, see
   <http://www.gnu.org/licenses/>.
   ====================================================================

*)

ParameterDefinitions = {
    {g1,        { Description -> "Hypercharge-Coupling"}},
    {g2,        { Description -> "Left-Coupling"}},
    {g3,        { Description -> "Strong-Coupling"}},
    {AlphaS,    { Description -> "Alpha Strong"}},
    {e,         { Description -> "electric charge"}},
    {Gf,        { Description -> "Fermi's constant"}},
    {aEWinv,    { Description -> "inverse weak coupling constant at mZ"}},
    {Yu,        { Description -> "Up-Yukawa-Coupling",
                  DependenceNum ->  Sqrt[2]/v* {{Mass[Fu,1],0,0},
                                                {0, Mass[Fu,2],0},
                                                {0, 0, Mass[Fu,3]}}}},
    {Yd,        { Description -> "Down-Yukawa-Coupling",
                  DependenceNum ->  Sqrt[2]/v* {{Mass[Fd,1],0,0},
                                                {0, Mass[Fd,2],0},
                                                {0, 0, Mass[Fd,3]}}}},
    {Ye,        { Description -> "Lepton-Yukawa-Coupling",
                  DependenceNum ->  Sqrt[2]/v* {{Mass[Fe,1],0,0},
                                                {0, Mass[Fe,2],0},
                                                {0, 0, Mass[Fe,3]}}}},
    {mu2,       { Description -> "SM Mu Parameter",
                  LaTeX -> "m^2",
                  OutputName -> mu2 }},
    {\[Lambda], { Description -> "SM Higgs Selfcouplings",
                  DependenceNum -> Mass[hh]^2/(2 v^2)}},
    {v,         { Description -> "EW-VEV",
                  DependenceNum -> Sqrt[4*Mass[VWp]^2/(g2^2)],
                  DependenceSPheno -> None  }},
    {ThetaW,    { Description -> "Weinberg-Angle",
                  DependenceNum -> ArcSin[Sqrt[1 - Mass[VWp]^2/Mass[VZ]^2]]  }},
    {ZZ,        { Description -> "Photon-Z Mixing Matrix"}},
    {ZW,        { Description -> "W Mixing Matrix",
                  Dependence ->   1/Sqrt[2] {{1, 1},
                                             {I,-I}} }},
    {Vu,        { Description ->"Left-Up-Mixing-Matrix"}},
    {Vd,        { Description ->"Left-Down-Mixing-Matrix"}},
    {Uu,        { Description ->"Right-Up-Mixing-Matrix"}},
    {Ud,        { Description ->"Right-Down-Mixing-Matrix"}},
    {Ve,        { Description ->"Left-Lepton-Mixing-Matrix"}},
    {Ue,        { Description ->"Right-Lepton-Mixing-Matrix"}},

(* split MSSM parameters *)

    {ZN,        { Description -> "Neutralino Mixing-Matrix" }},
    {UP,        { Description -> "Chargino-plus Mixing-Matrix" }},
    {UM,        { Description -> "Chargino-minus Mixing-Matrix" }},
    {ZE,        { Description -> "Slepton-Mixing-Matrix" }},
    {ZV,        { Description -> "Sneutrino Mixing-Matrix" }},
    {MassB,     { Description -> "Bino Mass parameter" }},
    {MassWB,    { Description -> "Wino Mass parameter" }},
    {\[Mu],         { Description -> "Mu-parameter",
                  Real -> True,
                  LaTeX -> "\\mu_{\\text{MSSM}}",
                  OutputName -> Mu }},
    {gYu,       { Description -> "Higgs-Bino-Up-Higgsino-Coupling",
                  Real -> True,
                  OutputName -> gYu,
                  LaTeX -> "\\tilde{g}_{1\\text{u}}",
                  LesHouches -> {SplitMSSM,1} }},
    {g2u,       { Description -> "Higgs-Wino-Up-Higgsino-Coupling",
                  Real -> True,
                  OutputName -> g2u,
                  LaTeX -> "\\tilde{g}_{2\\text{u}}",
                  LesHouches -> {SplitMSSM,2} }},
    {gYd,       { Description -> "Higgs-Bino-Down-Higgsino-Coupling",
                  Real -> True,
                  OutputName -> gYd,
                  LaTeX -> "\\tilde{g}_{1\\text{d}}",
                  LesHouches -> {SplitMSSM,3} }},
    {g2d,       { Description -> "Higgs-Wino-Down-Higgsino-Coupling",
                  Real -> True,
                  OutputName -> g2d,
                  LaTeX -> "\\tilde{g}_{2\\text{d}}",
                  LesHouches -> {SplitMSSM,4} }},
     
    {ml11,      { Description -> "Softbreaking left 1-1 generation Slepton Mass",
                  Real -> True,
                  OutputName -> ml11}},
    {ml12,      { Description -> "Softbreaking left 1-2 generation Slepton Mass",
                  Real -> True,
                  OutputName -> ml12 }},
    {ml21,      { Description -> "Softbreaking left 2-1 generation Slepton Mass",
                  Real -> True,
                  OutputName -> ml21 }},                           
    {ml22,      { Description -> "Softbreaking left 2-2 generation Slepton Mass",
                  Real -> True,
                  OutputName -> ml22 }},
                                                                                    
    {me11,      { Description -> "Softbreaking right 1-1 generation Slepton Mass",
                  Real -> True,
                  OutputName -> me11 }},
    {me12,      { Description -> "Softbreaking right 1-2 generation Slepton Mass",
                  Real -> True,
                  OutputName -> me12 }},
    {me21,      { Description -> "Softbreaking right 2-1 generation Slepton Mass",
                  Real -> True,
                  OutputName -> me21 }},
    {me22,      { Description -> "Softbreaking right 2-2 generation Slepton Mass",
                  Real -> True,
                  OutputName -> me22 }},
    
    {Te11,      { Description -> "Trilinear 1-1 Lepton-Coupling", 
                  Real -> True,
                  OutputName -> Te11 }}, 
    {Te12,      { Description -> "Trilinear 1-2 Lepton-Coupling",
                  Real -> True,
                  OutputName -> Te12 }},
    {Te21,      { Description -> "Trilinear 2-1 Lepton-Coupling",
                  Real -> True,
                  OutputName -> Te21 }},
    {Te22,      { Description -> "Trilinear 2-2 Lepton-Coupling",
                  Real -> True,
                  OutputName -> Te22 }},
    
    {g2llll,    { Description -> "Quartic-SU(2)-Left-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g2llll,
                  LaTeX -> "\\tilde{g}_{2,\\tilde{l}\\tilde{l}\\tilde{l}\\tilde{l}}",
                  LesHouches -> {SplitMSSM,5} }},

    {g2llhh,    { Description -> "Quartic-SU(2)-Higgs-Left-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g2llhh,
                  LaTeX -> "\\tilde{g}_{2,\\tilde{l}\\tilde{l}\\tilde{h}\\tilde{h}}",
                  LesHouches -> {SplitMSSM,6} }},

    {g2hhhh,    { Description -> "Quartic-SU(2)-Higgs-Coupling",
                  Real -> True,
                  OutputName -> g2hhhh,
                  LaTeX -> "\\tilde{g}_{2,\\tilde{h}\\tilde{h}\\tilde{h}\\tilde{h}}",
                  LesHouches -> {SplitMSSM,7} }},

    {g1llll11,  { Description -> "Quartic-U(1)-Left-1-1-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1llll11,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{l}\\tilde{l}\\tilde{l}\\tilde{l}}^{11}",
                  LesHouches -> {SplitMSSM,8} }},
    {g1llll12,  { Description -> "Quartic-U(1)-Left-1-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1llll12,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{l}\\tilde{l}\\tilde{l}\\tilde{l}}^{12}",
                  LesHouches -> {SplitMSSM,8} }},
    {g1llll22,  { Description -> "Quartic-U(1)-Left-2-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1llll22,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{l}\\tilde{l}\\tilde{l}\\tilde{l}}^{22}",
                  LesHouches -> {SplitMSSM,8} }},              

    {g1eeee11,  { Description -> "Quartic-U(1)-Right-1-1-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1eeee11,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{e}\\tilde{e}\\tilde{e}\\tilde{e}}^{11}",
                  LesHouches -> {SplitMSSM,9} }},
    {g1eeee12,  { Description -> "Quartic-U(1)-Right-1-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1eeee12,
                  LaTeX -> "\\tilde{g}_{2,\\tilde{e}\\tilde{e}\\tilde{e}\\tilde{e}}^{12}",
                  LesHouches -> {SplitMSSM,9} }},
    {g1eeee22,  { Description -> "Quartic-U(1)-Right-2-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1eeee22,
                  LaTeX -> "\\tilde{g}_{2,\\tilde{e}\\tilde{e}\\tilde{e}\\tilde{e}}^{22}",
                  LesHouches -> {SplitMSSM,9} }},

    {g1llhh1,   { Description -> "Quartic-U(1)-Higgs-Left-1-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1llhh1,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{l}\\tilde{l}\\tilde{h}\\tilde{h}}^1",
                  LesHouches -> {SplitMSSM,11} }},
    {g1llhh2,   { Description -> "Quartic-U(1)-Higgs-Left-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1llhh2,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{l}\\tilde{l}\\tilde{h}\\tilde{h}}^2",
                  LesHouches -> {SplitMSSM,11} }},

    {g1eehh1,   { Description -> "Quartic-U(1)-Higgs-Right-1-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1eehh1,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{e}\\tilde{e}\\tilde{h}\\tilde{h}}^1",
                  LesHouches -> {SplitMSSM,12} }},
    {g1eehh2,   { Description -> "Quartic-U(1)-Higgs-Right-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1eehh2,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{e}\\tilde{e}\\tilde{h}\\tilde{h}}^2",
                  LesHouches -> {SplitMSSM,12} }},

    {g1llee11,  { Description -> "Quartic-U(1)-Left-Right-1-1-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1llee11,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{l}\\tilde{l}\\tilde{e}\\tilde{e}}^{11}",
                  LesHouches -> {SplitMSSM,13} }},
    {g1llee12,  { Description -> "Quartic-U(1)-Left-Right-1-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1llee12,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{l}\\tilde{l}\\tilde{e}\\tilde{e}}^{12}",
                  LesHouches -> {SplitMSSM,13} }},
    {g1llee21,  { Description -> "Quartic-U(1)-Left-Right-2-1-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1llee21,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{l}\\tilde{l}\\tilde{e}\\tilde{e}}^{21}",
                  LesHouches -> {SplitMSSM,13} }},
    {g1llee22,  { Description -> "Quartic-U(1)-Left-Right-2-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> g1llee22,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{l}\\tilde{l}\\tilde{e}\\tilde{e}}^{22}",
                  LesHouches -> {SplitMSSM,13} }},
                
    {g2slwl1,   { Description -> "SU(2)-Slepton-Wino-Lepton-1-Coupling",
                  Real -> True,
                  OutputName -> g2slwl1,
                  LaTeX -> "\\tilde{g}_{2,\\tilde{l}\\tilde{W}l}^1",
                  LesHouches -> {SplitMSSM,14} }},
                  
    {g2slwl2,   { Description -> "SU(2)-Slepton-Wino-Lepton-2-Coupling",
                  Real -> True,
                  OutputName -> g2slwl2,
                  LaTeX -> "\\tilde{g}_{2,\\tilde{l}\\tilde{W}l}^2",
                  LesHouches -> {SplitMSSM,14} }},
                  
    {g1slbl1,   { Description -> "U(1)-Slepton-Bino-Lepton-1-Coupling",
                  Real -> True,
                  OutputName -> g1slbl1,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{l}\\tilde{B}l}^1",
                  LesHouches -> {SplitMSSM,15} }},
    {g1slbl2,   { Description -> "U(1)-Slepton-Bino-Lepton-2-Coupling",
                  Real -> True,
                  OutputName -> g1slbl2,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{l}\\tilde{B}l}^2",
                  LesHouches -> {SplitMSSM,15} }},
                  
    {g1sebe1,   { Description -> "U(1)-Selectron-Bino-Electron-1-Coupling",
                  Real -> True,
                  OutputName -> g1sebe1,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{e}\\tilde{B}e}^1",
                  LesHouches -> {SplitMSSM,16} }},
    {g1sebe2,   { Description -> "U(1)-Selectron-Bino-Electron-2-Coupling",
                  Real -> True,
                  OutputName -> g1sebe2,
                  LaTeX -> "\\tilde{g}_{1,\\tilde{e}\\tilde{B}e}^2",
                  LesHouches -> {SplitMSSM,16} }},
                  
    {gylele11,  { Description -> "Quartic-Yukawa-Left-Right-1-1-Slepton-Coupling",
                  Real -> True,
                  OutputName -> gylele11,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{l}\\tilde{e}\\tilde{l}\\tilde{e}}^{11}",
                  LesHouches -> {SplitMSSM,17} }},
    {gylele12,  { Description -> "Quartic-Yukawa-Left-Right-1-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> gylele12,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{l}\\tilde{e}\\tilde{l}\\tilde{e}}^{12}",
                  LesHouches -> {SplitMSSM,17} }},
    {gylele22,  { Description -> "Quartic-Yukawa-Left-Right-2-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> gylele22,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{l}\\tilde{e}\\tilde{l}\\tilde{e}}^{22}",
                  LesHouches -> {SplitMSSM,17} }},              
                  
    {gyllhh11,  { Description -> "Quartic-Yukawa-Higgs-Left-1-1-Slepton-Coupling",
                  Real -> True,
                  OutputName -> gyllhh11,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{l}\\tilde{l}\\tilde{h}\\tilde{h}}^{11}",
                  LesHouches -> {SplitMSSM,18} }},
    {gyllhh12,  { Description -> "Quartic-Yukawa-Higgs-Left-1-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> gyllhh12,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{l}\\tilde{l}\\tilde{h}\\tilde{h}}^{12}",
                  LesHouches -> {SplitMSSM,18} }},                  
    {gyllhh21,  { Description -> "Quartic-Yukawa-Higgs-Left-2-1-Slepton-Coupling",
                  Real -> True,
                  OutputName -> gyllhh21,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{l}\\tilde{l}\\tilde{h}\\tilde{h}}^{21}",
                  LesHouches -> {SplitMSSM,18} }},
    {gyllhh22,  { Description -> "Quartic-Yukawa-Higgs-Left-2-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> gyllhh22,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{l}\\tilde{l}\\tilde{h}\\tilde{h}}^{22}",
                  LesHouches -> {SplitMSSM,18} }},
                  
    {gyeehh11,  { Description -> "Quartic-Yukawa-Higgs-Right-1-1-Slepton-Coupling",
                  Real -> True,
                  OutputName -> gyeehh11,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{e}\\tilde{e}\\tilde{h}\\tilde{h}}^{11}",
                  LesHouches -> {SplitMSSM,19} }},
    {gyeehh12,  { Description -> "Quartic-Yukawa-Higgs-Right-1-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> gyeehh12,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{e}\\tilde{e}\\tilde{h}\\tilde{h}}^{12}",
                  LesHouches -> {SplitMSSM,19} }},                  
    {gyeehh21,  { Description -> "Quartic-Yukawa-Higgs-Right-2-1-Slepton-Coupling",
                  Real -> True,
                  OutputName -> gyeehh21,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{e}\\tilde{e}\\tilde{h}\\tilde{h}}^{21}",
                  LesHouches -> {SplitMSSM,19} }},
    {gyeehh22,  { Description -> "Quartic-Yukawa-Higgs-Right-2-2-Slepton-Coupling",
                  Real -> True,
                  OutputName -> gyeehh22,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{e}\\tilde{e}\\tilde{h}\\tilde{h}}^{22}",
                  LesHouches -> {SplitMSSM,19} }},                  

    {gyleh11,   { Description -> "Triple-Higgs-Slepton-Slepton-1-1-Coupling",
                  Real -> True,
                  OutputName -> gyleh11,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{l}\\tilde{e}\\tilde{h}}^{11}",
                  LesHouches -> {SplitMSSM,20} }},              
    {gyleh12,   { Description -> "Triple-Higgs-Slepton-Slepton-1-2-Coupling",
                  Real -> True,
                  OutputName -> gyleh12,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{l}\\tilde{e}\\tilde{h}}^{12}",
                  LesHouches -> {SplitMSSM,20} }},  
    {gyleh21,   { Description -> "Triple-Higgs-Slepton-Slepton-2-1-Coupling",
                  Real -> True,
                  OutputName -> gyleh21,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{l}\\tilde{e}\\tilde{h}}^{21}",
                  LesHouches -> {SplitMSSM,20} }},
    {gyleh22,   { Description -> "Triple-Higgs-Slepton-Slepton-2-2-Coupling",
                  Real -> True,
                  OutputName -> gyleh22,
                  LaTeX -> "\\tilde{g}_{y,\\tilde{l}\\tilde{e}\\tilde{h}}^{22}",
                  LesHouches -> {SplitMSSM,20} }},
                                                                           
    {gydsle1,   { Description -> "Triple-down-Higgsino-Slepton-Electron-1-Coupling",
                  Real -> True,
                  OutputName -> gYedsle1,
                  LaTeX -> "\\tilde{g}_{y_e,H_d\\tilde{l}e}^1",
                  LesHouches -> {SplitMSSM,21} }},
    {gydsle2,   { Description -> "Triple-down-Higgsino-Slepton-Electron-2-Coupling",
                  Real -> True,
                  OutputName -> gYedsle2,
                  LaTeX -> "\\tilde{g}_{y_e,H_d\\tilde{l}e}^2",
                  LesHouches -> {SplitMSSM,21} }},

    {gydlse1,   { Description -> "Triple-down-Higgsino-Electron-Right-Slepton-1-Coupling",
                  Real -> True,
                  OutputName -> gYedlse1,
                  LaTeX -> "\\tilde{g}_{y_e,H_dl\\tilde{e}}^1",
                  LesHouches -> {SplitMSSM,22} }},
    {gydlse2,   { Description -> "Triple-down-Higgsino-Electron-Right-Slepton-2-Coupling",
                  Real -> True,
                  OutputName -> gYedlse2,
                  LaTeX -> "\\tilde{g}_{y_e,H_dl\\tilde{e}}^2",
                  LesHouches -> {SplitMSSM,22} }}
};
