ParameterDefinitions = {
    {g1,        { Description -> "Hypercharge-Coupling"}},
    {g2,        { Description -> "Left-Coupling"}},
    {g3,        { Description -> "Strong-Coupling"}},
    {AlphaS,    { Description -> "Alpha Strong"}},
    {e,         { Description -> "electric charge"}},
    {Gf,        { Description -> "Fermi's constant"}},
    {aEWinv,    { Description -> "inverse weak coupling constant at mZ"}},
    {Yu,        { Description -> "Up-Yukawa-Coupling"}},
    {Yd,        { Description -> "Down-Yukawa-Coupling"}},
    {Ye,        { Description -> "Lepton-Yukawa-Coupling"}},
    {mH2,       { Description -> "SM Mu Parameter"}},
    {mS2,       { Description -> "Singlet mass parameter"}},
    {\[Lambda]1,{ Description -> "SM Higgs Selfcouplings"}},
    {\[Lambda]2,{ Description -> "Singlet 4-selfcoupling"}},
    {\[Lambda]3,{ Description -> "Singlet 2S-2H coupling"}},
    {\[Lambda]4,{ Description -> "Singlet S-2H coupling"}},
    {\[Lambda]5,{ Description -> "Singlet 3-selfcoupling"}},
    {vH,        { Description -> "EW-VEV"}},
    {vS,        { Description -> "Singlet-VEV",
                  DependenceSPheno -> None  }},
    {mH2,       { Description -> "SM Higgs Mass Parameter"}},
    {ThetaW,    { Description -> "Weinberg-Angle",
                  DependenceNum -> ArcSin[Sqrt[1 - Mass[VWp]^2/Mass[VZ]^2]]  }},
    {ZZ,        { Description -> "Photon-Z Mixing Matrix"}},
    {ZH,        { Description -> "Higgs Mixing Matrix"}},
    {ZW,        { Description -> "W Mixing Matrix",
                  Dependence ->   1/Sqrt[2] {{1, 1},
                                             {\[ImaginaryI],-\[ImaginaryI]}} }},
    {Vu,        { Description ->"Left-Up-Mixing-Matrix"}},
    {Vd,        { Description ->"Left-Down-Mixing-Matrix"}},
    {Uu,        { Description ->"Right-Up-Mixing-Matrix"}},
    {Ud,        { Description ->"Right-Down-Mixing-Matrix"}},
    {Ve,        { Description ->"Left-Lepton-Mixing-Matrix"}},
    {Ue,        { Description ->"Right-Lepton-Mixing-Matrix"}}
};
