
ParticleDefinitions[GaugeES] = {
      {SdL,  {  Description -> "Left Down-Squarks"}},
      {SdR,  { Description -> "Right Down-Squarks"}},
      {SuL,  { Description -> "Left Up-Squarks"}}, 
      {SuR,  { Description -> "Right Up-Squarks" }},                
      {SeL,  { Description -> "Left Selectron"}}, 
      {SeR,  { Description -> "Right Selectron"}},                         
      {SvL,  { Description -> "Left Sneutrino"}},                         
      {SHd0, { Description -> "Neutral Down-Higgs"}},                         
      {SHdm, { Description -> "Charged Down-Higgs"}}, 
      {SHu0, { Description -> "Neutral Up-Higgs"}},                         
      {SHup, { Description -> "Charged Up-Higgs"}},
      {SsR,  { Description -> "Singlet"}},            
      {SDxL,        {Description -> "Left SExotics",
                     FeynArtsNr -> 666,
	             LaTeX -> "\\tilde{Dx}_L",
                     OutputName -> "SDxL"}},
      {SDxbarR,     {Description -> "Right SExotics",
	             FeynArtsNr -> 667,
	             LaTeX -> "\\tilde{Dx}_R",
                     OutputName -> "SDxbR"}},
      {SH11I0,       {Description -> "Neutral Inert-Down1-Higgs",
  		     FeynArtsNr -> 101,
  		     LaTeX -> "h^{0Inert}_{11}",
                     OutputName -> "SH11I0" }},
      {SH11Im,  {     Description -> "Charged Inert-Down1-Higgs",
                     FeynArtsNr -> 102,
                     LaTeX -> "h^{-Inert}_{11}",
                     OutputName -> "SH11Im"}},
      {SH21I0,  {     Description -> "Neutral Inert-Up1-Higgs",
  		     FeynArtsNr -> 103,
  		     LaTeX -> "h^{0Inert}_{21}",
                     OutputName -> "SH21I0"}},
      {SH21Ip,  { Description -> "Charged Inert-Up1-Higgs",
  		     FeynArtsNr -> 104,
  		     LaTeX -> "h^{+Inert}_{21}",
                     OutputName -> "SH21Ip"}},
      {SH12I0,       {Description -> "Neutral Inert-Down2-Higgs",
  		     FeynArtsNr -> 9991,
  		     LaTeX -> "h^{0Inert}_{12}",
                     OutputName -> "SH12I0" }},
      {SH12Im,  {     Description -> "Charged Inert-Down2-Higgs",
                     FeynArtsNr -> 9992,
                     LaTeX -> "h^{-Inert}_{12}",
                     OutputName -> "SH12Im"}},
      {SH22I0,  {     Description -> "Neutral Inert-Up2-Higgs",
  		     FeynArtsNr -> 9993,
  		     LaTeX -> "h^{0Inert}_{22}",
                     OutputName -> "SH22I0"}},
      {SH22Ip,  { Description -> "Charged Inert-Up2-Higgs",
  		     FeynArtsNr -> 9994,
  		     LaTeX -> "h^{+Inert}_{22}",
                     OutputName -> "SH22Ip"}},
      {SsIR,   { Description -> "Inert-Singlet",
  		     FeynArtsNr -> 105,
  		     LaTeX -> "s^{Inert}",
                     OutputName -> "SSI"}},
       {SHpd0,   { Description -> "Neutral Prime-Higgs",
      		     FeynArtsNr -> 900,
      		     LaTeX -> "H^{'0}",
                     OutputName -> "SHpd0"}},
      {SHpdm,   {    Description -> "Negative charged Prime-Higgs",
      		     FeynArtsNr -> 901,
      		     LaTeX -> "H^{'-}",
                     OutputName -> "SHpdm"}},
      {SHpup,{ Description -> "Positive charged BarPrime-Higgs",
      		     FeynArtsNr -> 902,
      		     LaTeX -> "\\bar{H}^{'+}",
                     OutputName -> "SHpup"}},
      {SHpu0,{ Description -> "Neutral BarPrime-Higgs",
      		     FeynArtsNr -> 903,
      		     LaTeX -> "\\bar{H}^{'0}",
                     OutputName -> "SHpu0"}},    
      {VB,   { Description -> "B-Boson"}},             
      {VG,   { Description -> "Gluon"}},          
      {VWB,  { Description -> "W-Bosons"}},          
      {gB,   { Description -> "B-Boson Ghost"}},   
      {gG,   { Description -> "Gluon Ghost" }},          
      {gWB,  { Description -> "W-Boson Ghost"}},    
      {Glu,  { Description -> "Gluino"}},
      {Wino, { Description -> "Wino"}},
      {Bino, { Description -> "Bino"}},                          
      {H01,        { Description -> "Neutral down Higgsinos",
		     FeynArtsNr -> 122,
		     LaTeX -> "\\tilde{H}^0_1",
		     OutputName -> "H01"}},
      {HC1,         { Description -> "Charged down Higgsinos",
		      FeynArtsNr -> 123,
		      LaTeX -> "\\tilde{H}^-_1",
		      OutputName -> "HC1"}},
      {H02,         { Description -> "Neutral up Higgsinos",
		      FeynArtsNr -> 124,
		      LaTeX -> "\\tilde{H}^0_2",
		      OutputName -> "H02"}},
      {HC2,         { Description -> "Charged up Higgsinos",
		      FeynArtsNr -> 125,
		      LaTeX -> "\\tilde{H}^+_2",
		      OutputName -> "HC2"}},
      (* This does not work in the E6SSM because these can only be combined 
       after the U(1)N symmetry has been broken *) 
      (* {H0,   { Description -> "Neutral Higgsinos"}},
   {HC,   { Description -> "Charged Higgsinos"}},*)           
      (*  {FS,   { Description -> "Singlino" }}, *)
      {H01I1,    { Description -> "Neutral Inert-down-Higgsinos",
                     Width -> 0,
                     FeynArtsNr -> 721,
                     LaTeX -> "\\tilde{h}^{0,Inert}_1",
		    OutputName -> "HNI1"}},
      {HC1I1,    { Description -> "Charged Inert-down-Higgsinos",
                      Width -> 0,
                     FeynArtsNr -> 722,
                     LaTeX -> "\\tilde{h}^{-,Inert}_1",
		    OutputName -> "HCI11"}},
      {H01I2,    { Description -> "Neutral  Inert-up-Higgsinos",
                     Width -> 0,
                     FeynArtsNr -> 723,
                     LaTeX -> "\\tilde{h}^{0,Inert}_2",
		    OutputName -> "HNI21"}},
      {HC1I2,    { Description -> "Charged Inert-up-Higgsinos",
                     Width -> 0,
                     FeynArtsNr -> 724,
                     LaTeX -> "\\tilde{h}^{+}_2",
		    OutputName -> "HCI2"}}, 
      {H02I1,    { Description -> "Neutral Inert-down2-Higgsinos",
                     Width -> 0,
                     FeynArtsNr -> 999721,
                     LaTeX -> "\\tilde{h}^{0,Inert}_{12}",
		    OutputName -> "HN2I1"}},
      {HC2I1,    { Description -> "Charged Inert-down2-Higgsinos",
                      Width -> 0,
                     FeynArtsNr -> 999722,
                     LaTeX -> "\\tilde{h}^{-,Inert}_{12}",
		    OutputName -> "HC2I1"}},
      {H02I2,    { Description -> "Neutral  Inert-up2-Higgsinos",
                     Width -> 0,
                     FeynArtsNr -> 999723,
                     LaTeX -> "\\tilde{h}^{0,Inert}_{21}",
		    OutputName -> "HNI22"}},
      {HC2I2,    { Description -> "Charged Inert-up2-Higgsinos",
                     Width -> 0,
                     FeynArtsNr -> 999724,
                     LaTeX -> "\\tilde{h}^{+}_{22}",
		    OutputName -> "HCI22"}}, 
      {Hp0,    { Description -> "Neutral Prime-Higgsinos",
                     Width -> 0,
                     FeynArtsNr -> 950,
                     LaTeX -> "\\tilde{h}^{'0}",
		    OutputName -> "HpN"}},
      {HpC,    { Description -> "Charged Prime-Higgsinos",
                 Width -> 0,
                 FeynArtsNr -> 951,
                 LaTeX -> "\\tilde{h}^{'-}",
                 OutputName -> "HpC"}},
      {Hp01,    { Description -> "Neutral Prime-Higgsinos",
                     Width -> 0,
                     FeynArtsNr -> 950,
                     LaTeX -> "\\tilde{h}^{'0}_1",
		    OutputName -> "HNP1"}},
      {HpC1,    { Description -> "Charged Prime-Higgsinos",
                     Width -> 0,
                     FeynArtsNr -> 951,
                     LaTeX -> "\\tilde{h}^{'-}_1",
		    OutputName -> "HCP1"}},
      {Hp02,    { Description -> "Neutral  Prime-Bar-Higgsinos",
                     Width -> 0,
                     FeynArtsNr -> 952,
                     LaTeX -> "\\tilde{\\bar{h}}^{'0}_2",
		    OutputName -> "HNP2"}},
      {HpC2,    { Description -> "Charged Prime-Bar-Higgsinos",
                     Width -> 0,
                     FeynArtsNr -> 953,
                     LaTeX -> "\\tilde{\\bar{h}}^{'+}_2",
		    OutputName -> "HCP2"}},
      (*  {FDX,        { Description -> "Dirac Exotics",
        	     LaTeX -> "x_1",
		     FeynArtsNr -> 660,
                         OutputName -> "FDx"}}, *)
      {FDx1,        { Description -> "Dirac Left Exotics",
        	     LaTeX -> "Dx_1",
		     FeynArtsNr -> 660,
		     OutputName -> "Dx1"}},
      {FDx2,        { Description -> "Dirac Right Exotics",
        	     LaTeX -> "Dx_2",
		     FeynArtsNr -> 661,
		     OutputName -> "Dx2"}},
      {FS1,        { Description -> "Dirac Left Singlino",
		     FeynArtsNr -> 806,
  		     LaTeX -> "\\tilde{s}_L",
		     OutputName -> "FSL"}},
      {FS2,        { Description -> "Dirac Right Singlino",
		     FeynArtsNr -> 807,
  		     LaTeX -> "\\tilde{s}_R",
		     OutputName -> "FSR"}},
      {FSI1,    { Description -> "Inert-Singlino-1",
                      FeynArtsNr -> 905,
                      LaTeX -> "\\tilde{S}^{Inert}_1",
                      OutputName -> "FSI1"}},
      {FSI2,    { Description -> "Inert-Singlino-2",
                      FeynArtsNr -> 905,
                      LaTeX -> "\\tilde{S}^{Inert}_2",
                      OutputName -> "FSI2"}},
      {Fd1,  { Description -> "Dirac Left Down-Quark"}},
      {Fd2,  { Description -> "Dirac Right Down-Quark"}},
      {Fu1,  { Description -> "Dirac Left Up-Quark"}},
      {Fu2,  { Description -> "Dirac Right Up-Quark"}},
      {Fe1,  { Description -> "Dirac Left Electron"}},
      {Fe2,  { Description -> "Dirac Right Electron"}},
      {Fv,   { Description -> "Neutrinos" }},
      {VBp,   { LaTeX -> "Bp",
               OutputName -> "VBp",
               FeynArtsNr -> 10 }},
      {gBp,   { LaTeX -> "g_Bp",
               OutputName -> "gBp",
               FeynArtsNr -> 10 }},
      {FBp,  { LaTeX -> "\\tilde{Bp}_1",
               FeynArtsNr -> 10,
               OutputName -> "FBp"}}
      };
      
      
  ParticleDefinitions[TEMP] = {
    {VZ,   { Description -> "Z-Boson" }}, 
    {gZ,   { Description -> "Z-Boson Ghost" }}
    };
      
      
  ParticleDefinitions[EWSB] = {

     {Sd ,  { Description -> "Down-Squarks"}},
     {Su ,  { Description -> "Up-Squarks"}},   
     {Se ,  { Description -> "Sleptons"}}, 
     {Sv ,  { Description -> "Sneutrinos"}}, 
     {SDX,   { Description -> "SExotics",
              PDG -> {1000051,2000051,1000052,2000052,1000053,2000053},
              Mass -> Automatic,
              ElectricCharge -> -1/3,
              FeynArtsNr -> 666,
              LaTeX -> "\\tilde{x}",
              OutputName -> "SX"}},
     {FSI,  { Description -> "Inert-Singlino",
              PDG -> {1000089,1000090},
              FeynArtsNr -> 105,
              ElectricCharge -> 0,
              LaTeX -> "\\tilde{S}^{Inert}",
              OutputName -> "FSI"}},
     {hh   ,  {  Description -> "Higgs", 
                 PDG -> {25,35,45,55,65,75,85},  
                 PDG.IX ->{101000001,101000002,101000003,101000004,101000004,101000006,101000007} }}, 
{Ah   ,  {    Description -> "Pseudo-Scalar Higgs",
              PDG -> {0, 0, 36, 225,335,445,555},
              PDG.IX ->{0, 0, 36, 225,335,445,555} }},                

               
  (* {hh ,  { Description -> "Higgs", 
              PDG -> {25, 35,45},
              PDG.IX ->{101000001,101000002,101000003} }}, 
     {Ah ,  { Description -> "Pseudo-Scalar Higgs", 
              LaTeX -> "A",
              PDG -> {0, 0, 36},
              PDG.IX ->{0,0, 102000001},
              FeynArtsNr -> 2 }}, *)                      
     {Hpm,  { Description -> "Charged Higgs",
              PDG -> {0, -37, -10289781, -10289782, -10289783,-10289784},
              PDG.IX ->{0, -100000601,-10289781, -10289782, -10289783,-10289784}}},   
     {SSI0,   { Description -> "Inert-Singlet",
                    PDG -> {89,90},
                    FeynArtsNr -> 105,
                    ElectricCharge -> 0,
                    LaTeX -> "s^{Inert}",
                    OutputName -> "SSI"}},
      {SsIR,  { Description -> "Inert-Singlet",
               PDG -> {89,90},
               FeynArtsNr -> 105,
               ElectricCharge -> 0,
               LaTeX -> "s^{Inert}",
               OutputName -> "SSI"}},
      {SHp0,   { Description -> "Neutral Prime-Higgs",
                     PDG -> {92,94},
      		     FeynArtsNr -> 900,
		     ElectricCharge -> 0,
      		     LaTeX -> "H^{'0}",
		     OutputName -> "HPN"}},
      {SHpp,   { Description -> "Charged Prime-Higgs",
                     PDG -> {91,93},
		     ElectricCharge -> -1,
      		     FeynArtsNr -> 901,
      		     LaTeX -> {"H^{'-}","H^{'+}"},
		     OutputName -> "HPA"}},
      {VP,   { Description -> "Photon"}},
      {VZp,    { Description -> "Z'-Boson"}},  
      {gZp,    { Description -> "Z'-Ghost" }},  
      {VZ,   { Description -> "Z-Boson" }}, 
      {gZ,   { Description -> "Z-Boson Ghost" }},  
      {VG,   { Description -> "Gluon" }},          
      {VWm,  { Description -> "W-Boson" }},         
      {gP,   { Description -> "Photon Ghost"}}, 
      {gWm,  { Description -> "Negative W-Boson Ghost"}}, 
      {gWmC, { Description -> "Positive W-Boson Ghost" }}, 
      {gG,   { Description -> "Gluon Ghost" }},                 
      {Fd,   { Description -> "Down-Quarks"}},   
      {Fu,   { Description -> "Up-Quarks"}},   
      {Fe,   { Description -> "Leptons" }},
      {Fv,   { Description -> "Neutrinos" }}, 
      {FDX,  { Description->"Exotics",
    		   PDG -> {51,52,53},
    		   Width -> 0,
    		   Mass -> Automatic,
		   ElectricCharge -> -1/3,
    		   FeynArtsNr -> 666,
    		   LaTeX -> "x",
    		   OutputName -> "FDX"}},
       {FSI,    { Description -> "Inert-Singlino",
                  FeynArtsNr -> 806,
                  LaTeX -> "\\tilde{S}^{Inert}",
                  OutputName -> "FSI"}},
      {Glu,  { Description -> "Gluino" }},
      {Chi,  { Description -> "Neutralinos",
               PDG -> {1000022,1000023,1000025,1000035,1000045,1000055,1000065,1000075, 1000085,1000095},
               PDG.IX ->{211000001,211000002,211000003,211000004,211000005,211000006, 211000007,211000008, 211000009,211000011},
               FeynArtsNr -> 11 }},
     {Cha,  { Description -> "Charginos",
              PDG -> {-1666124, -1666137, -1666178,-1666179  },
              PDG.IX ->{-210000601,-210000602,-2166178,-2166179},
              FeynArtsNr -> 12}},
      {ChiP,   { Description -> "Prime Neutralinos",
                     PDG -> {1000092,1000094},
		     ElectricCharge -> 0,
      		     FeynArtsNr -> 900,
      		     LaTeX -> "\\tilde{\\chi}^{'0}",
		     OutputName -> "NP"}},
      {ChaP,   { Description -> "Prime Chargino",
                     PDG -> {1000091},
		     ElectricCharge -> -1,
    		     (*Mass -> Automatic,*)
      		     FeynArtsNr -> 901,
      		     LaTeX -> {"\\tilde{\\chi}^{'-}",
      			       "\\tilde{\\chi}^{'+}"},
		     OutputName -> "ChaP"}}                            
        };    
                
 WeylFermionAndIndermediate = {
       {FHd0,  { Description -> "Neutral Down-Higgsino"}},      
       {FHu0,  { Description -> "Neutral Up-Higgsino" }}, 
       {FHdm,  { Description -> "Charged Down-Higgsino"}}, 
       {FHup,  { Description -> "Charged Up-Higgsino"}},
       {FHpd0, { Description -> "Neutral Higgsino-Prime",
                     FeynArtsNr -> 1053,
                     LaTeX -> "\\tilde{h'}^{0}"}},
       {FHpu0, { Description -> "Neutral Higgsino-Bar-Prime",
                 FeynArtsNr -> 1063,
                 LaTeX -> "\\tilde{\\bar{h'}}^{0}"}},
       {FHpdm, { Description -> "Charged Higgsino-Prime",
                 FeynArtsNr -> 1054,
                 LaTeX -> "\\tilde{h'}^{0}"}},
       {FHpup, { Description -> "Charged Higgsino-Bar-Prime",
                 FeynArtsNr -> 1064,
                 LaTeX -> "\\tilde{\\bar{h'}^}{+}"}},
       {FH11I0, { Description -> "Neutral Inert-down1-Higgsino",
                     FeynArtsNr -> 821,
                     LaTeX -> "\\tilde{h}^{0,Inert}_{d1}"}},
       {FH21I0, { Description -> "Neutral Inert-up-Higgsino",
                     FeynArtsNr -> 823,
                     LaTeX -> "\\tilde{h}^{0,Inert}_{u1}"}},
       {FH11Im, { Description -> "Charged Inert-down-Higgsino1",
                     FeynArtsNr -> 822,
                     LaTeX -> "\\tilde{h}^{-,Inert}_{d1}"}},
       {FH21Ip, { Description -> "Charged Inert-up-Higgsino1",
                     FeynArtsNr -> 824,
                     LaTeX -> "\\tilde{h}^{+,Inert}_{u1}"}},
       {FH12I0, { Description -> "Neutral Inert-down2-Higgsino",
                     FeynArtsNr -> 99921,
                     LaTeX -> "\\tilde{h}^{0,Inert}_{d1}"}},
       {FH22I0, { Description -> "Neutral Inert-up2-Higgsino",
                     FeynArtsNr -> 99923,
                     LaTeX -> "\\tilde{h}^{0,Inert}_{u2}"}},
       {FH12Im, { Description -> "Charged Inert-down2-Higgsino1",
                     FeynArtsNr -> 99922,
                     LaTeX -> "\\tilde{h}^{-,Inert}_{d2}"}},
       {FH22Ip, { Description -> "Charged Inert-up-Higgsino2",
                     FeynArtsNr -> 99924,
                     LaTeX -> "\\tilde{h}^{+,Inert}_{u2}"}},
       {FsIR,    { Description -> "Weyl-Inert-Singlino",
                       PDG -> {1000089,1000090},
                       FeynArtsNr -> 205,
                       LaTeX -> "\\tilde{S}^{Inert}",
                       OutputName -> "FS0I"}},
       {L0,    { Description -> "Neutralino Weyl-Spinor"}},
       {Lm,    { Description -> "Negative Chargino Weyl-Spinor"}},
       {Lp,    { Description -> "Positive Chargino Weyl-Spinor"}}, 
       {L0I,   { Description -> "Neutralino Inert-Weyl-Spinor"}},
       {LmI,    { Description -> "Negative Chargino Inert-Weyl-Spinor"}},
       {LpI,    { Description -> "Positive Chargino Inert-Weyl-Spinor"}},
       {L0p,    { Description -> "Neutralino Prime-Weyl-Spinor"}},
       {fG,    { Description ->"Gluino Weyl-Spinor"}},
       {fWB,   { Description ->"Wino Weyl-Spinor"}},
       {fW0,   { Description ->"Neutral Wino" }},
       {fWm,   { Description ->"Negative Wino"}},                 
       {fWp,   { Description ->"Positive Wino"}},                 
       {fB,    { Description ->"Bino Weyl-Spinor"}},    
       {phid,  { Description -> "Scalar Down"}},                                                                       
       {phiu,  { Description -> "Scalar Up"}}, 
       {sigmad,   { Description -> "Pseudo Scalar Down"}},                                                                                        
       {sigmau,   { Description -> "Pseudo Scalar Up" }},
       
       {SHd,  { Description -> "Down-Higgs"}},
       {SHu,  { Description -> "Up-Higgs"}},
       {Sl,   { Description -> "Left Slepton" }},
       {Sq,   { Description -> "Left Squark" }},
       {FeL,  { Description -> "Left Electron" }},
       {FeR,  { Description -> "Right Electron" }} ,
       {FdL,  { Description -> "Left Down-Quark" }},
       {FdR,  { Description -> "Right Down-Quark" }},              
       {FuL,  { Description -> "Left Up-Quark" }},
       {FuR,  { Description -> "Right Up-Quark" }},
       {FEL,  { Description -> "Rotated Left Electron" }},
       {FER,  { Description -> "Rotated Right Electron" }} ,
       {FDL,  { Description -> "Rotated Left Up-Quark" }},
       {FDR,  { Description -> "Rotated Right Up-Quark" }},              
       {FUL,  { Description -> "Rotated Left Down-Quark"}},
       {FUR,  { Description -> "Rotated Right Down-Quark" }},                
       {FHd,  { Description -> "Down-Higgsino" }},
       {FHu,  { Description -> "Up-Higgsino" }},
       {Fl,   { Description -> "Left Leptons"}},
       {Fq,   { Description -> "Left Quarks"}}, 
       {FvL,  { Description -> "Left Neutrino"}}, 
       {FsR,   { Description -> "Weyl Spinor of Singlino"}}, 
       
       {fBp,   { LaTeX -> "\\lambda_Bp" }},
       {FDXL,   { Description -> "Rotated Left Exotics",
                 LaTeX -> "X_L"}},
       {FDXR,   { Description->"Rotated Right Exotics",
                 LaTeX -> "X_L"}},         
       {sigmaS,      {Description -> "Pseudo Scalar Singlet" }}  ,
       {sigmaI11,      {Description -> "PseudoScalar Singlet I11",
                       Width -> 0, 
                       Mass -> Automatic,
                       LaTeX -> "\\sigma_{I11}",
                       OutputName -> "" }}  ,   
       {sigmaI22,      {Description -> "Pseudo Scalar Singlet I22",
                       Width -> 0, 
                       Mass -> Automatic,
                       LaTeX -> "\\sigma_{I22}",
                       OutputName -> "" }}  ,   
       {sigmaI12,      {Description -> "PseudoScalar Singlet I12",
                       Width -> 0, 
                       Mass -> Automatic,
                       LaTeX -> "\\sigma_{I12}",
                       OutputName -> "" }}  ,   
       {sigmaI21,      {Description -> "Pseudo Scalar Singlet I21",
                       Width -> 0, 
                       Mass -> Automatic,
                       LaTeX -> "\\sigma_{I21}",
                       OutputName -> "" }}  ,   
       {phiS,      { Description -> " Scalar Singlet"}},

       {phiI11,      { Description -> " Scalar Singlet I11",
                      Width -> 0, 
                      Mass -> Automatic,
                      LaTeX -> "\\phi_{I11}",
                      OutputName -> ""  }},
       {phiI22,      { Description -> " Scalar Singlet I22",
                      Width -> 0, 
                      Mass -> Automatic,
                      LaTeX -> "\\phi_{I22}",
                      OutputName -> "" }},
        {phiI12,      { Description -> " Scalar Singlet I12",
                      Width -> 0, 
                      Mass -> Automatic,
                      LaTeX -> "\\phi_{I12}",
                      OutputName -> ""  }},
       {phiI21,      { Description -> " Scalar Singlet I21",
                      Width -> 0, 
                      Mass -> Automatic,
                      LaTeX -> "\\phi_{I21}",
                      OutputName -> "" }},
       
       {e,    { Description -> "Right Electron Superfield" }},
       {d,    { Description -> "Right Down-Quark Superfield" }},                 
       {q,    { Description -> "Left Quark Superfield" }},                 
       {u,    { Description -> "Right Up-Quark Superfield" }},                 
       {l,    { Description -> "left Lepton Superfield" }},  
       {Hd,   { Description -> "Down-Higgs Superfield"}},                                         
       {Hu,   { Description -> "Up-Higgs Superfield" }},                 
       {s,    { Description -> "Singlet Superfield" }}, 
       {G,    { Description -> "Gluon Superfield" }},                 
       {B,    { Description -> "B Superfield" }},                 
       {WB,   { Description -> "W Superfield" }},
       {Bp,    { Description -> "U(1)' gauge Superfield", 
                 LaTeX -> "\\hat{Bp}"}},
      {H1I,    { Description -> "Inert-Down-Higgs Superfield",
		     LaTeX -> "\\hat{H}^{Inert}_{1}"}},
      {H1,    { Description -> "Inert-Up-Higgs Superfield",
		     LaTeX -> "\\hat{H}^{Inert}_{2}"}},
      {sI,     { Description -> "Inert-Singlet Superfield",
		     LaTeX -> "\\hat{S}^{Inert}"}},    
       {MassZp,    { LaTeX -> "M_{Zp}",
                    Form -> Scalar }},
      {SH1I,   { Description-> "Scalar Inert Down Higgs",
		     LaTeX -> "H^{Inert}_1"}},
      {SH2I,   { Description-> "Scalar Inert Up Higgs",
		     LaTeX -> "H^{Inert}_2"}},
      {SHp,   { Description-> "Scalar Prime Higgs",
		     LaTeX -> "H'"}},
      {SHpbar,   { Description-> "Scalar Bar Prime Higgs",
		     LaTeX -> "\\bar{H'}"}},
      {Dx,          { Description -> "Left Exotics Superfield",
		     LaTeX -> "\\hat{Dx}"}},
      {Dxbar,       { Description -> "Right Exotics Superfield",
		     LaTeX -> "\\hat{\\bar{Dx}}"}},
        {Hp,          { Description -> "HPrime Superfield",
                     LaTeX -> "\\hat{H'}"}},
      {Hpbar,       { Description -> "HPrimeBar Superfield",
                     LaTeX -> "\\hat{\\bar{H'}}"}}
};       


